eureka:
    client:
        serviceUrl:
          defaultZone: http://localhost:8761/eureka/
server:
    port: 8769
spring:
    application:
      name: sc-zuul
zuul:
    routes:
        api-a:
            path: /api-ribbon/**
            serviceId: sc-ribbon
        api-b:
            path: /api-feign/**
            serviceId: sc-feign