server:
  port: 8762

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
  environment: dev
spring:
  application:
    name: sc-hi
  redis:
    host: 10.9.20.61
    port: 7379 #primary
#    port: 7380 # slave
    password: Fpyadmin@321