server:
  port: 8762

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
  environment: dev
spring:
  application:
    name: sc-hi
  redis:
    host: 10.1.5.251
    port: 6380